//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TP1_PW3Model", "FK_equipo_torneo", "torneo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entidades.torneo), "equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entidades.equipo), true)]
[assembly: EdmRelationshipAttribute("TP1_PW3Model", "FK_jugador_equipo", "equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Entidades.equipo), "jugador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Entidades.jugador), true)]

#endregion

namespace Entidades
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TP1_PW3Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TP1_PW3Entities object using the connection string found in the 'TP1_PW3Entities' section of the application configuration file.
        /// </summary>
        public TP1_PW3Entities() : base("name=TP1_PW3Entities", "TP1_PW3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TP1_PW3Entities object.
        /// </summary>
        public TP1_PW3Entities(string connectionString) : base(connectionString, "TP1_PW3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TP1_PW3Entities object.
        /// </summary>
        public TP1_PW3Entities(EntityConnection connection) : base(connection, "TP1_PW3Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comentario> comentarios
        {
            get
            {
                if ((_comentarios == null))
                {
                    _comentarios = base.CreateObjectSet<comentario>("comentarios");
                }
                return _comentarios;
            }
        }
        private ObjectSet<comentario> _comentarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<equipo> equipoes
        {
            get
            {
                if ((_equipoes == null))
                {
                    _equipoes = base.CreateObjectSet<equipo>("equipoes");
                }
                return _equipoes;
            }
        }
        private ObjectSet<equipo> _equipoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<jugador> jugadors
        {
            get
            {
                if ((_jugadors == null))
                {
                    _jugadors = base.CreateObjectSet<jugador>("jugadors");
                }
                return _jugadors;
            }
        }
        private ObjectSet<jugador> _jugadors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<torneo> torneos
        {
            get
            {
                if ((_torneos == null))
                {
                    _torneos = base.CreateObjectSet<torneo>("torneos");
                }
                return _torneos;
            }
        }
        private ObjectSet<torneo> _torneos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuario>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuario> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comentarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomentarios(comentario comentario)
        {
            base.AddObject("comentarios", comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the equipoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToequipoes(equipo equipo)
        {
            base.AddObject("equipoes", equipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the jugadors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojugadors(jugador jugador)
        {
            base.AddObject("jugadors", jugador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the torneos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotorneos(torneo torneo)
        {
            base.AddObject("torneos", torneo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuario usuario)
        {
            base.AddObject("usuarios", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP1_PW3Model", Name="comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comentario object.
        /// </summary>
        /// <param name="idComentario">Initial value of the idComentario property.</param>
        /// <param name="cFecha">Initial value of the cFecha property.</param>
        /// <param name="cDetalle">Initial value of the cDetalle property.</param>
        /// <param name="cNombre">Initial value of the cNombre property.</param>
        /// <param name="cEmail">Initial value of the cEmail property.</param>
        public static comentario Createcomentario(global::System.Int32 idComentario, global::System.DateTime cFecha, global::System.String cDetalle, global::System.String cNombre, global::System.String cEmail)
        {
            comentario comentario = new comentario();
            comentario.idComentario = idComentario;
            comentario.cFecha = cFecha;
            comentario.cDetalle = cDetalle;
            comentario.cNombre = cNombre;
            comentario.cEmail = cEmail;
            return comentario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idComentario
        {
            get
            {
                return _idComentario;
            }
            set
            {
                if (_idComentario != value)
                {
                    OnidComentarioChanging(value);
                    ReportPropertyChanging("idComentario");
                    _idComentario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idComentario");
                    OnidComentarioChanged();
                }
            }
        }
        private global::System.Int32 _idComentario;
        partial void OnidComentarioChanging(global::System.Int32 value);
        partial void OnidComentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime cFecha
        {
            get
            {
                return _cFecha;
            }
            set
            {
                OncFechaChanging(value);
                ReportPropertyChanging("cFecha");
                _cFecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cFecha");
                OncFechaChanged();
            }
        }
        private global::System.DateTime _cFecha;
        partial void OncFechaChanging(global::System.DateTime value);
        partial void OncFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cDetalle
        {
            get
            {
                return _cDetalle;
            }
            set
            {
                OncDetalleChanging(value);
                ReportPropertyChanging("cDetalle");
                _cDetalle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cDetalle");
                OncDetalleChanged();
            }
        }
        private global::System.String _cDetalle;
        partial void OncDetalleChanging(global::System.String value);
        partial void OncDetalleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cNombre
        {
            get
            {
                return _cNombre;
            }
            set
            {
                OncNombreChanging(value);
                ReportPropertyChanging("cNombre");
                _cNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cNombre");
                OncNombreChanged();
            }
        }
        private global::System.String _cNombre;
        partial void OncNombreChanging(global::System.String value);
        partial void OncNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cEmail
        {
            get
            {
                return _cEmail;
            }
            set
            {
                OncEmailChanging(value);
                ReportPropertyChanging("cEmail");
                _cEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cEmail");
                OncEmailChanged();
            }
        }
        private global::System.String _cEmail;
        partial void OncEmailChanging(global::System.String value);
        partial void OncEmailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP1_PW3Model", Name="equipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class equipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new equipo object.
        /// </summary>
        /// <param name="idEquipo">Initial value of the idEquipo property.</param>
        /// <param name="eNombre">Initial value of the eNombre property.</param>
        public static equipo Createequipo(global::System.Int32 idEquipo, global::System.String eNombre)
        {
            equipo equipo = new equipo();
            equipo.idEquipo = idEquipo;
            equipo.eNombre = eNombre;
            return equipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEquipo
        {
            get
            {
                return _idEquipo;
            }
            set
            {
                if (_idEquipo != value)
                {
                    OnidEquipoChanging(value);
                    ReportPropertyChanging("idEquipo");
                    _idEquipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEquipo");
                    OnidEquipoChanged();
                }
            }
        }
        private global::System.Int32 _idEquipo;
        partial void OnidEquipoChanging(global::System.Int32 value);
        partial void OnidEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String eNombre
        {
            get
            {
                return _eNombre;
            }
            set
            {
                OneNombreChanging(value);
                ReportPropertyChanging("eNombre");
                _eNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("eNombre");
                OneNombreChanged();
            }
        }
        private global::System.String _eNombre;
        partial void OneNombreChanging(global::System.String value);
        partial void OneNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eIdTorneo
        {
            get
            {
                return _eIdTorneo;
            }
            set
            {
                OneIdTorneoChanging(value);
                ReportPropertyChanging("eIdTorneo");
                _eIdTorneo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eIdTorneo");
                OneIdTorneoChanged();
            }
        }
        private Nullable<global::System.Int32> _eIdTorneo;
        partial void OneIdTorneoChanging(Nullable<global::System.Int32> value);
        partial void OneIdTorneoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP1_PW3Model", "FK_equipo_torneo", "torneo")]
        public torneo torneo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<torneo>("TP1_PW3Model.FK_equipo_torneo", "torneo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<torneo>("TP1_PW3Model.FK_equipo_torneo", "torneo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<torneo> torneoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<torneo>("TP1_PW3Model.FK_equipo_torneo", "torneo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<torneo>("TP1_PW3Model.FK_equipo_torneo", "torneo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP1_PW3Model", "FK_jugador_equipo", "jugador")]
        public EntityCollection<jugador> jugadors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<jugador>("TP1_PW3Model.FK_jugador_equipo", "jugador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<jugador>("TP1_PW3Model.FK_jugador_equipo", "jugador", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP1_PW3Model", Name="jugador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class jugador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new jugador object.
        /// </summary>
        /// <param name="idJugador">Initial value of the idJugador property.</param>
        /// <param name="jNombre">Initial value of the jNombre property.</param>
        /// <param name="jApellido">Initial value of the jApellido property.</param>
        /// <param name="jEdad">Initial value of the jEdad property.</param>
        public static jugador Createjugador(global::System.Int64 idJugador, global::System.String jNombre, global::System.String jApellido, global::System.DateTime jEdad)
        {
            jugador jugador = new jugador();
            jugador.idJugador = idJugador;
            jugador.jNombre = jNombre;
            jugador.jApellido = jApellido;
            jugador.jEdad = jEdad;
            return jugador;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idJugador
        {
            get
            {
                return _idJugador;
            }
            set
            {
                if (_idJugador != value)
                {
                    OnidJugadorChanging(value);
                    ReportPropertyChanging("idJugador");
                    _idJugador = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idJugador");
                    OnidJugadorChanged();
                }
            }
        }
        private global::System.Int64 _idJugador;
        partial void OnidJugadorChanging(global::System.Int64 value);
        partial void OnidJugadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jNombre
        {
            get
            {
                return _jNombre;
            }
            set
            {
                OnjNombreChanging(value);
                ReportPropertyChanging("jNombre");
                _jNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jNombre");
                OnjNombreChanged();
            }
        }
        private global::System.String _jNombre;
        partial void OnjNombreChanging(global::System.String value);
        partial void OnjNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String jApellido
        {
            get
            {
                return _jApellido;
            }
            set
            {
                OnjApellidoChanging(value);
                ReportPropertyChanging("jApellido");
                _jApellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("jApellido");
                OnjApellidoChanged();
            }
        }
        private global::System.String _jApellido;
        partial void OnjApellidoChanging(global::System.String value);
        partial void OnjApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime jEdad
        {
            get
            {
                return _jEdad;
            }
            set
            {
                OnjEdadChanging(value);
                ReportPropertyChanging("jEdad");
                _jEdad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jEdad");
                OnjEdadChanged();
            }
        }
        private global::System.DateTime _jEdad;
        partial void OnjEdadChanging(global::System.DateTime value);
        partial void OnjEdadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> jIdEquipo
        {
            get
            {
                return _jIdEquipo;
            }
            set
            {
                OnjIdEquipoChanging(value);
                ReportPropertyChanging("jIdEquipo");
                _jIdEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jIdEquipo");
                OnjIdEquipoChanged();
            }
        }
        private Nullable<global::System.Int32> _jIdEquipo;
        partial void OnjIdEquipoChanging(Nullable<global::System.Int32> value);
        partial void OnjIdEquipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP1_PW3Model", "FK_jugador_equipo", "equipo")]
        public equipo equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<equipo>("TP1_PW3Model.FK_jugador_equipo", "equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<equipo>("TP1_PW3Model.FK_jugador_equipo", "equipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<equipo> equipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<equipo>("TP1_PW3Model.FK_jugador_equipo", "equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<equipo>("TP1_PW3Model.FK_jugador_equipo", "equipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP1_PW3Model", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP1_PW3Model", Name="torneo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class torneo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new torneo object.
        /// </summary>
        /// <param name="idTorneo">Initial value of the idTorneo property.</param>
        /// <param name="tNombre">Initial value of the tNombre property.</param>
        /// <param name="tActivo">Initial value of the tActivo property.</param>
        /// <param name="tPrecio">Initial value of the tPrecio property.</param>
        public static torneo Createtorneo(global::System.Int32 idTorneo, global::System.String tNombre, global::System.Boolean tActivo, global::System.Decimal tPrecio)
        {
            torneo torneo = new torneo();
            torneo.idTorneo = idTorneo;
            torneo.tNombre = tNombre;
            torneo.tActivo = tActivo;
            torneo.tPrecio = tPrecio;
            return torneo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTorneo
        {
            get
            {
                return _idTorneo;
            }
            set
            {
                if (_idTorneo != value)
                {
                    OnidTorneoChanging(value);
                    ReportPropertyChanging("idTorneo");
                    _idTorneo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTorneo");
                    OnidTorneoChanged();
                }
            }
        }
        private global::System.Int32 _idTorneo;
        partial void OnidTorneoChanging(global::System.Int32 value);
        partial void OnidTorneoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tNombre
        {
            get
            {
                return _tNombre;
            }
            set
            {
                OntNombreChanging(value);
                ReportPropertyChanging("tNombre");
                _tNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tNombre");
                OntNombreChanged();
            }
        }
        private global::System.String _tNombre;
        partial void OntNombreChanging(global::System.String value);
        partial void OntNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean tActivo
        {
            get
            {
                return _tActivo;
            }
            set
            {
                OntActivoChanging(value);
                ReportPropertyChanging("tActivo");
                _tActivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tActivo");
                OntActivoChanged();
            }
        }
        private global::System.Boolean _tActivo;
        partial void OntActivoChanging(global::System.Boolean value);
        partial void OntActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal tPrecio
        {
            get
            {
                return _tPrecio;
            }
            set
            {
                OntPrecioChanging(value);
                ReportPropertyChanging("tPrecio");
                _tPrecio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tPrecio");
                OntPrecioChanged();
            }
        }
        private global::System.Decimal _tPrecio;
        partial void OntPrecioChanging(global::System.Decimal value);
        partial void OntPrecioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TP1_PW3Model", "FK_equipo_torneo", "equipo")]
        public EntityCollection<equipo> equipoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<equipo>("TP1_PW3Model.FK_equipo_torneo", "equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<equipo>("TP1_PW3Model.FK_equipo_torneo", "equipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TP1_PW3Model", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the idUsuario property.</param>
        /// <param name="uApellido">Initial value of the uApellido property.</param>
        /// <param name="uNombre">Initial value of the uNombre property.</param>
        /// <param name="uEmail">Initial value of the uEmail property.</param>
        /// <param name="uContrasenia">Initial value of the uContrasenia property.</param>
        public static usuario Createusuario(global::System.Int32 idUsuario, global::System.String uApellido, global::System.String uNombre, global::System.String uEmail, global::System.String uContrasenia)
        {
            usuario usuario = new usuario();
            usuario.idUsuario = idUsuario;
            usuario.uApellido = uApellido;
            usuario.uNombre = uNombre;
            usuario.uEmail = uEmail;
            usuario.uContrasenia = uContrasenia;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idUsuario
        {
            get
            {
                return _idUsuario;
            }
            set
            {
                if (_idUsuario != value)
                {
                    OnidUsuarioChanging(value);
                    ReportPropertyChanging("idUsuario");
                    _idUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idUsuario");
                    OnidUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _idUsuario;
        partial void OnidUsuarioChanging(global::System.Int32 value);
        partial void OnidUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uApellido
        {
            get
            {
                return _uApellido;
            }
            set
            {
                OnuApellidoChanging(value);
                ReportPropertyChanging("uApellido");
                _uApellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uApellido");
                OnuApellidoChanged();
            }
        }
        private global::System.String _uApellido;
        partial void OnuApellidoChanging(global::System.String value);
        partial void OnuApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uNombre
        {
            get
            {
                return _uNombre;
            }
            set
            {
                OnuNombreChanging(value);
                ReportPropertyChanging("uNombre");
                _uNombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uNombre");
                OnuNombreChanged();
            }
        }
        private global::System.String _uNombre;
        partial void OnuNombreChanging(global::System.String value);
        partial void OnuNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uEmail
        {
            get
            {
                return _uEmail;
            }
            set
            {
                OnuEmailChanging(value);
                ReportPropertyChanging("uEmail");
                _uEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uEmail");
                OnuEmailChanged();
            }
        }
        private global::System.String _uEmail;
        partial void OnuEmailChanging(global::System.String value);
        partial void OnuEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String uContrasenia
        {
            get
            {
                return _uContrasenia;
            }
            set
            {
                OnuContraseniaChanging(value);
                ReportPropertyChanging("uContrasenia");
                _uContrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("uContrasenia");
                OnuContraseniaChanged();
            }
        }
        private global::System.String _uContrasenia;
        partial void OnuContraseniaChanging(global::System.String value);
        partial void OnuContraseniaChanged();

        #endregion

    
    }

    #endregion

    
}
