//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name ObtenerEquiposResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        TP1.ServiceReference1.ObtenerEquiposResponse ObtenerEquipos(TP1.ServiceReference1.ObtenerEquiposRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquipos", Namespace="http://tempuri.org/", Order=0)]
        public TP1.ServiceReference1.ObtenerEquiposRequestBody Body;
        
        public ObtenerEquiposRequest() {
        }
        
        public ObtenerEquiposRequest(TP1.ServiceReference1.ObtenerEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEquiposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool incluirDeTorneosInactivos;
        
        public ObtenerEquiposRequestBody() {
        }
        
        public ObtenerEquiposRequestBody(bool incluirDeTorneosInactivos) {
            this.incluirDeTorneosInactivos = incluirDeTorneosInactivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP1.ServiceReference1.ObtenerEquiposResponseBody Body;
        
        public ObtenerEquiposResponse() {
        }
        
        public ObtenerEquiposResponse(TP1.ServiceReference1.ObtenerEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerEquiposResult;
        
        public ObtenerEquiposResponseBody() {
        }
        
        public ObtenerEquiposResponseBody(string ObtenerEquiposResult) {
            this.ObtenerEquiposResult = ObtenerEquiposResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : TP1.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<TP1.ServiceReference1.Service1Soap>, TP1.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP1.ServiceReference1.ObtenerEquiposResponse TP1.ServiceReference1.Service1Soap.ObtenerEquipos(TP1.ServiceReference1.ObtenerEquiposRequest request) {
            return base.Channel.ObtenerEquipos(request);
        }
        
        public string ObtenerEquipos(bool incluirDeTorneosInactivos) {
            TP1.ServiceReference1.ObtenerEquiposRequest inValue = new TP1.ServiceReference1.ObtenerEquiposRequest();
            inValue.Body = new TP1.ServiceReference1.ObtenerEquiposRequestBody();
            inValue.Body.incluirDeTorneosInactivos = incluirDeTorneosInactivos;
            TP1.ServiceReference1.ObtenerEquiposResponse retVal = ((TP1.ServiceReference1.Service1Soap)(this)).ObtenerEquipos(inValue);
            return retVal.Body.ObtenerEquiposResult;
        }
    }
}
